apiVersion: v1
kind: Service
metadata:
  name: ubuntu-pod
spec:
  selector:
    app: demoapp   
  ports: 
  - port: 8080
    targetPort: 80
  type: Loadbalancer

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: demoapp
spec:   
  containers: 
  - image: ramadevidyuthi2021/ubuntu4.0
    name: ubuntu-pod
    ports: 
    - containerPort:80
